[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Axel Lindeberg <axel.ew.lindeberg@gmail.com>"]
edition = "2021"
default-run = "aoc2021"

[dependencies]
itertools = "0.10"
hashbrown = "0.11"
regex = "1.5"
once_cell = "1.9"
